server:
  port: 8096
  tomcat: 
    max-swallow-size: -1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fakecloudtest
    username: postgres
    password: Jay40984692
    driverClassName: org.postgresql.Driver
    # url: jdbc:mysql://localhost:3306/bookingtest
    # username: root
    # password: Jay40984692$
    # driverClassName: com.mysql.jdbc.Driver
  # redis:
  #   datasource:
  #     host: 127.0.0.1
  #     port: 6379
  #     username: redis
  #     password: admin1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      database: 3
      host: 127.0.0.1
      username: redis
      password: admin1234
      timeout: 1800
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

logging:
  level:
    org: WARN
    hibernate:
      SQL: DEBUG
      type:
        descriptor: TRACE
    blog: WARN
    springframework: 
      security: DEBUG



jwt:
  secret: "tz6sAA3jZxcamyqGVwShXl7MqACyE26WYRwrHl8FO1A="
  expiration: 2592000000 # 30 days in milliseconds